#!/usr/bin/python
#
# Tool for processing the CMU Pronunciation Dictionary file formats.
#
# Copyright (C) 2015 Reece H. Dunn
#
# This file is part of cmudict-tools.
#
# cmudict-tools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cmudict-tools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cmudict-tools.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import print_function

import cmudict
import sys

dict_formats = { # {0} = word ; {1} = context ; {2} = phonemes ; {3} = comment
	'cmudict-wade': {
		'comment': '##{3}',
		'entry': '{0}  {2}',
		'entry-context': '{0}({1})  {2}',
		'phonemes': lambda phonemes: ' '.join(phonemes),
	},
	'cmudict': {
		'comment': ';;;{3}',
		'entry': '{0}  {2}',
		'entry-context': '{0}({1})  {2}',
		'phonemes': lambda phonemes: ' '.join(phonemes),
	},
	'cmudict-new': {
		'comment': ';;;{3}',
		'entry': '{0} {2}',
		'entry-context': '{0}({1}) {2}',
		'phonemes': lambda phonemes: ' '.join(phonemes),
	},
}

def print_dict(filename, opts={}):
	fmt = dict_formats[opts.get('format', 'cmudict')]
	phonemeset = fmt['phonemes']

	for word, context, phonemes, comment, error in cmudict.parse_cmudict(filename):
		if error:
			print(error, file=sys.stderr)
			continue
		components = []
		if word:
			components.append('entry')
		if context:
			components.append('context')
		if comment != None:
			components.append('comment')
		if phonemes:
			phonemes = phonemeset(phonemes)
		if len(components) == 0:
			print()
		else:
			print(fmt['-'.join(components)].format(word, context, phonemes, comment))

def debug(filename, opts={}):
	for entry in cmudict.parse_cmudict(filename):
		print(entry)

def validate(filename, opts={}):
	for word, context, phonemes, comment, error in cmudict.parse_cmudict(filename):
		if error:
			print(error, file=sys.stderr)

commands = {
	'debug':    debug,
	'validate': validate,
	'print':    print_dict,
}

try:
	command = None
	filename = None
	optname = None
	opts = {}
	for arg in sys.argv[1:]:
		if arg.startswith('--'):
			arg = arg[2:]
			if '=' in arg:
				arg, value = arg.split('=')
			else:
				value = None
			if arg in ['format']:
				if value:
					opts[arg] = value
				else:
					optname = arg
		elif optname:
			opts[optname] = arg
			optname = None
		elif not command:
			command = commands[arg]
		elif not filename:
			filename = arg
		else:
			raise Exception('invalid argument')
except:
	print('usage: cmudict-tools debug    <filename>')
	print('usage: cmudict-tools validate <filename>')
	print('usage: cmudict-tools print    <filename>')
	sys.exit(1)

command(filename, opts)
