#!/usr/bin/python
# coding=utf-8
#
# Concept Mapping Metadata parser.
#
# Copyright (C) 2016 Reece H. Dunn
#
# This file is part of cmudict-tools.
#
# cmudict-tools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cmudict-tools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cmudict-tools.  If not, see <http://www.gnu.org/licenses/>.

import sys
import json

from cmudicttools import metadata

print(json.dumps(metadata.parse_mapping(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]), sort_keys=True))
